######################################################################
# Automatically generated by qmake (3.0) dt. nov. 7 15:38:34 2017
######################################################################

TEMPLATE = app
TARGET = dialogoPersonalizado
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
QT += widgets
