######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 17:18:45 2017
######################################################################

TEMPLATE = app
TARGET = 04-FindDialog
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
QT += widgets
