######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 16:08:40 2017
######################################################################

TEMPLATE = app
TARGET = 02-Connections
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
QT += widgets
