######################################################################
# Automatically generated by qmake (3.0) dt. des. 5 16:21:04 2017
######################################################################

TEMPLATE = app
TARGET = Editor
INCLUDEPATH += .

# Input
HEADERS += finddialog.h mainwindow.h
SOURCES += finddialog.cpp main.cpp mainwindow.cpp
QT += widgets
