######################################################################
# Automatically generated by qmake (3.0) dt. nov. 21 16:00:34 2017
######################################################################

TEMPLATE = app
TARGET = Editor
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
QT += widgets
