######################################################################
# Automatically generated by qmake (3.0) dt. des. 12 17:06:12 2017
######################################################################

TEMPLATE = app
TARGET = Editor
INCLUDEPATH += .

# Input
HEADERS += DialogoDeshacer.h finddialog.h mainwindow.h
FORMS += DialogoDeshacer.ui
SOURCES += DialogoDeshacer.cpp finddialog.cpp main.cpp mainwindow.cpp
QT += widgets
