######################################################################
# Automatically generated by qmake (3.0) dt. gen. 23 15:14:56 2018
######################################################################

TEMPLATE = app
TARGET = Bolas
INCLUDEPATH += .

# Input
HEADERS += Bola.h Dialog.h DInfoTabla.h MainWindow.h
FORMS += Dialog.ui DInfoTabla.ui
SOURCES += Bola.cpp Dialog.cpp DInfoTabla.cpp main.cpp MainWindow.cpp
QT += widgets
