######################################################################
# Automatically generated by qmake (3.0) dt. gen. 9 15:17:50 2018
######################################################################

TEMPLATE = app
TARGET = Bolas
INCLUDEPATH += .

# Input
HEADERS += Bola.h MainWindow.h
SOURCES += Bola.cpp main.cpp MainWindow.cpp
QT += widgets
