######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 16:30:41 2017
######################################################################

TEMPLATE = app
TARGET = 03-LayingOutWidgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
