######################################################################
# Automatically generated by qmake (3.0) dt. nov. 14 16:04:21 2017
######################################################################

TEMPLATE = app
TARGET = calculadora
INCLUDEPATH += .

# Input
HEADERS += calculadora.h
FORMS += calculadora.ui
SOURCES += calculadora.cpp main.cpp
QT += widgets
