######################################################################
# Automatically generated by qmake (3.0) dt. nov. 14 17:41:06 2017
######################################################################

TEMPLATE = app
TARGET = calculadora
INCLUDEPATH += .

# Input
HEADERS += calculadora.h xarxa.h
FORMS += calculadora.ui xarxa.ui
SOURCES += calculadora.cpp main.cpp xarxa.cpp
QT += widgets
